"""Agregado campo nombre a la tabla Certificado

Revision ID: 4c729daf7e88
Revises: b62305cbe462
Create Date: 2024-11-21 22:48:30.820348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c729daf7e88'
down_revision = 'b62305cbe462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
